jobs:
  del_runs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
        repository: ${{ github.repository }}
        retain_days: ${{ github.event.inputs.days }}
        token: ${{ github.token }}
name: delete-workflow-runs
on:
  repository_dispatch:
    types: trigger-ga___delete-workflow-runs.yml
