jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: git checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: get latest jdk ga
      uses: oracle-actions/setup-java@v1
      with:
        release: 21
        website: jdk.java.net
    - continue-on-error: true
      name: cache maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      name: build with maven
      run: mvn -B clean install -P pre-release -pl '!karate-gatling' -Djavacpp.platform=linux-x86_64
    timeout-minutes: 10
name: jdk-compat
on:
  repository_dispatch:
    types: trigger-ga___jdk-compat.yml
