jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: git checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up jdk 11
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: cache maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-maven-
    - continue-on-error: true
      name: build with maven
      run: mvn -B clean install -P pre-release -Djavacpp.platform=linux-x86_64
    - continue-on-error: true
      name: build and test with docker
      run: ./build-docker.sh
    - continue-on-error: true
      if: ${{ false }}
      name: upload workspace if build fails
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: .
        retention-days: 5
    timeout-minutes: 20
name: maven-build
on:
  repository_dispatch:
    types: trigger-ga___maven-build.yml
