jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: git checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up jdk 11
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        java-version: 11
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: set maven version
      run: 'mvn versions:set versions:commit -B -ntp -DnewVersion=${{ github.event.inputs.version
        }}

        '
    - continue-on-error: true
      name: docker build
      run: 'mvn clean install -B -ntp -DskipTests -P pre-release

        ./build-docker.sh

        '
    - continue-on-error: true
      name: docker login
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      name: docker push
      run: 'docker tag karate-chrome karatelabs/karate-chrome:${{ github.event.inputs.version
        }}

        docker tag karate-chrome karatelabs/karate-chrome:latest

        docker push karatelabs/karate-chrome:${{ github.event.inputs.version }}

        docker push karatelabs/karate-chrome:latest

        '
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: maven deploy to central
      run: 'mvn -B -ntp deploy -DskipTests -P pre-release,release

        '
    - continue-on-error: true
      name: maven build binaries
      run: 'mvn package -DskipTests -P fatjar -f karate-core/pom.xml

        mvn package -DskipTests -P fatjar -f karate-robot/pom.xml

        '
    - continue-on-error: true
      name: upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: karate-release-${{ github.event.inputs.version }}
        path: "karate-core/target/*.jar\nkarate-robot/target/*.jar  \n"
        retention-days: 5
    timeout-minutes: 20
name: maven-release
on:
  repository_dispatch:
    types: trigger-ga___maven-release.yml
